demoapi/demoapi/urls.py
from django.contrib import admin
from django.urls import path
from course.views import GetAllCourseAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/', GetAllCourseAPIView.as_view())
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('detail/<int:question_id>', views.detailView, name="detail"),
    path('list/', views.view_list, name='view_list'),
    path('', views.index, name="index"),
    path('<int:question_id>', views.vote, name='vote')
]

shoppingsite/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

polls/models.py
from django.db import models

# Create your models here.

class Questions(models.Model):
    question_text = models.CharField(max_length=200)
    time_pub = models.DateTimeField()

class Choice(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)
    

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from.models import Questions

# Create your views here.
def index(request):
    myname = "Bảo Hưng"
    taisan = ["Điện thoại", "máy tính", "máy bay", "nhiều tiền"]
    context = {"name": myname, "taisan": taisan}
    return render(request, "polls/index.html", context)

def view_list(request):
    #get_object_or_404(Questions, pk=5)
    list_question = Questions.objects.all()
    context = {"dsquest": list_question}
    return render(request, "polls/question_list.html", context)

def detailView(request, question_id):
    q = Questions.objects.get(pk=question_id)
    return render(request, "polls/detail_question.html", {"qs": q})

def vote(request, question_id):
    q = Questions.objects.get(pk=question_id)
    try:
        dulieu = request.POST["choice"]
        c = q.choice_set.get(pk=dulieu)
    except:
        return HttpResponse("Lỗi không có choice")
    c.vote = c.vote +1
    c.save()
    return render(request, "polls/result.html", {"q": q})

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/polls/style.css' %}">
</head>
<body>
    <div class="header"> 
        <h1>My Website</h1>
    </div>
    <div class="menu">
        <ul>
            <li>Link 1</li>
            <li>Link 2</li>
            <li>Link 3</li>
            <li>Link 4</li>
        </ul>
    </div>
    <div class="content"> 
        {% block content123 %}      
        {% endblock %}
    </div>
</body>
</html>

polls/templates/polls/detail_question.html
{% extends 'polls/base.html' %}

{% block content123 %}      
    {% if qs %}
    <h1>{{qs.question_text}}</h1>
    <form action="{% url 'polls:vote' qs.id %}" method="post">
        {% csrf_token %}
        <ul>
        {% for item in qs.choice_set.all %}
            <li><input type="radio" value="{{ item.id}}" name="choice">{{item.choice_text}}</li>
        {% endfor %}
            <p><input type="submit" value="gửi"></p>
        </ul>
    </form>
    {% endif%}
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content123  %}

<h1>Đây là template</h1>
<p>Chào các bạn mình là  <b>{{ name }}</b></p>
<h2>Tài sản của tôi gồm: </h2>
<ul>
    {% for item in taisan %}
        {% if item != 'máy tính' %}
            <li>{{ item }}</li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock %}

polls/templates/polls/question_list.html
{% extends 'polls/base.html' %}

{% block content123 %}      
    {% if dsquest %}
        {% for item in dsquest %}
            <a href="{%url 'polls:detail' item.id%}"><p>{{ item.question_text }}</p></a>
        {% endfor%}
    {% else %}
        <h3 style="color: red;">Không có dữ liệu câu hỏi nào !!!</h3>
    {% endif%}
{% endblock %}

polls/templates/polls/result.html
{% extends 'polls/base.html' %}

{% block content123 %}  
    {% if q %}
        <h1>{{ q.question_text}}</h1>
        <p>Kết quả của cuộc bình chọn là: </p>
        {% for item in q.choice_set.all%}
            <p>{{item.choice_text}} : <span style="color: red;">{{item.vote}}</span></p>
        {% endfor %}
        <a href="{% url 'polls:view_list'%}">Vote tiếp</a>
    {% endif %}
{% endblock %}