demoapi/demoapi/urls.py
from django.contrib import admin
from django.urls import path
from course.views import GetAllCourseAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/', GetAllCourseAPIView.as_view())
]

loginDemo/demoLogin/Login/urls.py
from django.urls import path
from .views import IndexClass, LoginClass, ViewUser, view_product, AddPost

app_name = 'Login'
urlpatterns = [
    path('', IndexClass.as_view(), name='index'),
    path('login/', LoginClass.as_view(), name='login'),
    path('user-view/', ViewUser.as_view(), name='user_view'),
    path('view-pro/', view_product, name='view-product'),
    path('add-post/', AddPost.as_view(), name='add_post')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('detail/<int:question_id>', views.detailView, name="detail"),
    path('list/', views.view_list, name='view_list'),
    path('', views.index, name="index"),
    path('<int:question_id>', views.vote, name='vote')
]

shoppingsite/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

loginDemo/demoLogin/Login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class MyUser(AbstractUser):
    sex_choice = ((0, "Nữ"),(1, "nam"), (2, "Khác"))
    age = models.IntegerField(default=0)
    sex = models.IntegerField(choices=sex_choice, default=0)
    address = models.CharField(default='', max_length=255)

loginDemo/demoLogin/Login/forms.py
from attr import field
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content',]

loginDemo/demoLogin/Login/views.py
from django.shortcuts import render, HttpResponse
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, decorators
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm


# Create your views here.
class IndexClass(View):
    def get(self, request):
        return HttpResponse("<h1>Xin chao</h1>")


class LoginClass(View):
    def get(self, request):
        return render(request, template_name='Login/login.html')

    def post(self, request):
        username = request.POST.get("tendangnhap")
        password = request.POST.get("password")
        my_user = authenticate(username= username, password= password)
        if my_user is None:
            return HttpResponse(f"Dang nhap that bai User {username} khong ton tai")

        login(request, my_user)
        return render(request, 'Login/success.html')

class ViewUser(LoginRequiredMixin, View):
    login_url= '/login/'
    def get(self, request):
        return HttpResponse("<h1>Day la view user </h1>")
    
    def post(self, request):
        pass

@decorators.login_required(login_url='/login/')
def view_product(request):
    return HttpResponse('Xem san pham')


class AddPost(LoginRequiredMixin, View):
    login_url = '/login/'
    def get(self, request):
        f = PostForm()
        context = {'fm': f}
        return render(request, 'Login/add_post.html', context)

    def post(self, request):
        f = PostForm(request.POST)
        if not f.is_valid():
            return HttpResponse('Ban nhap sai du lieu')
        #check user permission
        print(request.user.get_all_permissions())
        if request.user.has_perm('Login.add_post'):
            f.save()
        else: 
            return HttpResponse('Ban chua duoc cap quyen')
        return HttpResponse("Oke")

loginDemo/demoLogin/Login/templates/Login/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'Login:add_post' %}" method="post">
        {%csrf_token%}
        {{fm}}
        <input type="submit" value="ADD">

    </form>
</body>
</html>

loginDemo/demoLogin/Login/templates/Login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="Login">
        <form action="", method="post">
            <input type="text" name="tendangnhap">
            <input type="password" name="password">
            <input type="submit" value="Dang nhap">
            {%csrf_token%}
        </form>
    </div>
</body>
</html>

loginDemo/demoLogin/Login/templates/Login/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        .message{
            color: red;
        }
    </style>
</head>
<body>
    <div class="message">
        <h3>Đăng nhập thành công</h3>
    </div>
</body>
</html>