demoapi/demoapi/urls.py
from django.contrib import admin
from django.urls import path
from course.views import GetAllCourseAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/', GetAllCourseAPIView.as_view())
]

djangoProject/demoform/news/urls.py
from django.urls import path
from . import views
app_name="news"
urlpatterns = [
    path('', views.IndexClass.as_view(), name='index'),
    #path('add/', views.PostClass.as_view(), name="add"),
    path('save/',views.ClassSaveNews.as_view(), name="save"),
    path('email/', views.email_view, name='email'),
    path('process/', views.prosess, name="pro")
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('detail/<int:question_id>', views.detailView, name="detail"),
    path('list/', views.view_list, name='view_list'),
    path('', views.index, name="index"),
    path('<int:question_id>', views.vote, name='vote')
]

shoppingsite/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

djangoProject/demoform/news/models.py
#from asyncio import FastChildWatcher
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.TextField(max_length=1000, blank=False, null=False)
    time_created = models.DateTimeField(default=timezone.datetime.now())

    def __str__(self):
        return self.title

djangoProject/demoform/news/forms.py
from attr import attr
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content','time_created',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'tieude123'}),
            'content': forms.Textarea(attrs={'class': 'noidung204000'})
        }


class SendEmail(forms.Form):
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'tieude'}))
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'baohung', 'id':'noidung'}))
    cc = forms.BooleanField(required=False)

djangoProject/demoform/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from requests import request
from .forms import PostForm, SendEmail
from django.views import View

# Create your views here.
class IndexClass(View):
    def get(self, request):
        ketqua = "1233232345"
        return HttpResponse(ketqua)

# class PostClass(View):
#     def get(self, request):
#         a = PostForm()
#         return render(request, 'news/add_news.html', {'f': a})

class ClassSaveNews(View):
    def get(self, request):
        a = PostForm()
        return render(request, 'news/add_news.html', {'f': a})

    def post(self, request):
        g = PostForm(request.POST)
        if g.is_valid():
            g.save()
            return HttpResponse('Luu oke')
        else:
            return HttpResponse('Khong duoc validate')
    
    def put(self):
        pass

def email_view(request):
    b = SendEmail
    return render(request, 'news/email.html', {'f': b})

def prosess(request):
    if request.method == "POST":
        m = SendEmail(request.POST)
        if m.is_valid():
            # tieude = m.cleaned_data['title']
            # cc = m.cleaned_data['cc']
            # noidung = m.cleaned_data['content']
            # email = m.cleaned_data['email']
            # context = { 'td':tieude, 'c': cc, 'b': noidung, 'd': email}
            context2 = {'email_data': m}
            return render(request, 'news/print_email.html', context2)
        else:
            return HttpResponse('Form not validate')
    else:
        return HttpResponse('Không phải POST method')
            

djangoProject/demoform/news/templates/news/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'news:save' %}" method="post">
        <p>{{ f.title }}</p>
        <p>{{ f.content }}</p>
        <p>{{f.time_created}}</p>
        {% csrf_token %}
        <input type="submit" value="Thêm">
    </form>
</body>
</html>

djangoProject/demoform/news/templates/news/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <style>
        .baohung{
            padding: 40px;
        }
    </style>
</head>
<body>
    <form action="{% url 'news:pro' %}" method="post">
        {{f}}
        {% csrf_token %}
        <input type="submit" value="Gửi mail"> 
        
    </form>
</body>
</html>

djangoProject/demoform/news/templates/news/print_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        td{
            border: 1px solid #000;
        }
    </style>
</head>
<body>
    <table>
        <tr>
            <td>Tiêu đề</td>
            <td>Nội dung</td>
            <td>Email</td>
            <td>cc</td>
        </tr>
        <tr>
            <td>{{email_data.title }}</td>
            <td>{{email_data.email }}</td>
            <td>{{email_data.content }}</td>
            <td>{{email_data.cc }}</td>
        </tr>
    </table>
</body>
</html>